/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

import java.sql.*;
import java.awt.*;
import java.util.Properties;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import java.util.*;
import javax.activation.*;  
import static pms.Nurse.buildTableModel;

/**
 *
 * @author Abid
 */
public class Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Doctor
     */
    UtilDateModel model;
    Properties px;
    JDatePanelImpl datePanel;
    JDatePickerImpl datePicker;
    ResultSet rss,res;
    Connection co=null;
    public Doctor() {
        co=SqlConn.dbCon();
        try
        {
            rss=co.prepareStatement("select id,name from info").executeQuery();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        try
        {
            res=co.prepareStatement("select vid, pid, did, datetime from visits").executeQuery();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        initComponents();
        jPanel3.setBackground(new Color(0,0,0,100));
        jPanel7.setVisible(false);
        jPanel11.setVisible(false);
        jPanel12.setVisible(false);
        jPanel14.setVisible(false);
        jPanel15.setVisible(false);
        
        model = new UtilDateModel();
		Properties px = new Properties();
		px.put("text.today", "Today");
		px.put("text.month", "Month");
		px.put("text.year", "Year");
		datePanel = new JDatePanelImpl(model, px);
		// Don't know about the formatter, but there it is...
		datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
		datePicker.setBounds(410, 90, 170, 30);
                
                jPanel11.add(datePicker);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton7 = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Clock_32px.png"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 10, 32, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New session");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(50, 15, 90, 16);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 250, 50);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Heart_with_Pulse_32px_1.png"))); // NOI18N
        jPanel8.add(jLabel6);
        jLabel6.setBounds(10, 10, 32, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Patient Record");
        jPanel8.add(jLabel7);
        jLabel7.setBounds(50, 15, 110, 16);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 50, 250, 50);

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Add_User_Male_32px_1.png"))); // NOI18N
        jPanel10.add(jLabel10);
        jLabel10.setBounds(10, 10, 32, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Add patient");
        jPanel10.add(jLabel11);
        jLabel11.setBounds(50, 15, 90, 16);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(0, 100, 250, 50);

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Change_User_32px.png"))); // NOI18N
        jPanel9.add(jLabel8);
        jLabel8.setBounds(10, 10, 32, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Update patient record");
        jPanel9.add(jLabel9);
        jLabel9.setBounds(50, 15, 160, 16);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 150, 250, 50);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Feedback_32px.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel31);
        jLabel31.setBounds(190, 340, 40, 40);

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.setLayout(null);
        jPanel14.add(jTextField11);
        jTextField11.setBounds(9, 11, 200, 40);

        jButton4.setBackground(new java.awt.Color(204, 0, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Send");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton4);
        jButton4.setBounds(10, 60, 63, 29);

        jPanel1.add(jPanel14);
        jPanel14.setBounds(10, 280, 220, 100);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jButton5.setBackground(new java.awt.Color(204, 0, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add Visit");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(250, 300, 90, 23);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField12);
        jTextField12.setBounds(20, 40, 60, 20);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel32.setText("Patient ID");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(20, 20, 60, 16);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel33.setText("Doctor ID");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(100, 20, 60, 16);
        jPanel6.add(jTextField13);
        jTextField13.setBounds(100, 40, 60, 20);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel34.setText("BP");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(20, 90, 20, 16);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField14);
        jTextField14.setBounds(20, 110, 60, 20);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel35.setText("RBC");
        jPanel6.add(jLabel35);
        jLabel35.setBounds(90, 90, 40, 16);
        jPanel6.add(jTextField15);
        jTextField15.setBounds(90, 110, 60, 20);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel36.setText("WBC");
        jPanel6.add(jLabel36);
        jLabel36.setBounds(163, 90, 50, 16);
        jPanel6.add(jTextField16);
        jTextField16.setBounds(160, 110, 70, 20);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel37.setText("BRate");
        jPanel6.add(jLabel37);
        jLabel37.setBounds(240, 90, 60, 16);
        jPanel6.add(jTextField17);
        jTextField17.setBounds(240, 110, 70, 20);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel38.setText("HRate");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(320, 90, 60, 16);
        jPanel6.add(jTextField18);
        jTextField18.setBounds(320, 110, 70, 20);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel39.setText("Sugar");
        jPanel6.add(jLabel39);
        jLabel39.setBounds(400, 90, 80, 16);
        jPanel6.add(jTextField19);
        jTextField19.setBounds(400, 110, 90, 20);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel40.setText("Temp");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(500, 90, 50, 16);
        jPanel6.add(jTextField20);
        jTextField20.setBounds(500, 110, 90, 20);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel41.setText("Amount Spent");
        jPanel6.add(jLabel41);
        jLabel41.setBounds(180, 20, 90, 16);
        jPanel6.add(jTextField21);
        jTextField21.setBounds(180, 40, 80, 20);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel42.setText("Patient Remarks");
        jPanel6.add(jLabel42);
        jLabel42.setBounds(20, 160, 100, 16);
        jPanel6.add(jTextField22);
        jTextField22.setBounds(20, 180, 570, 20);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel43.setText("Doctor's Remarks");
        jPanel6.add(jLabel43);
        jLabel43.setBounds(20, 230, 110, 16);
        jPanel6.add(jTextField23);
        jTextField23.setBounds(20, 250, 570, 20);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 10, 610, 350);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(null);

        jLabel44.setText("Blood Pressure");
        jPanel15.add(jLabel44);
        jLabel44.setBounds(40, 10, 110, 14);

        jLabel45.setText("Breathing Rate");
        jPanel15.add(jLabel45);
        jLabel45.setBounds(40, 50, 110, 14);

        jLabel46.setText("Heart Rate");
        jPanel15.add(jLabel46);
        jLabel46.setBounds(40, 90, 90, 14);

        jLabel47.setText("Sugar Levels");
        jPanel15.add(jLabel47);
        jLabel47.setBounds(40, 130, 100, 14);

        jLabel48.setText("Body Temperature");
        jPanel15.add(jLabel48);
        jLabel48.setBounds(40, 170, 140, 14);

        jLabel49.setText("WBC Count");
        jPanel15.add(jLabel49);
        jLabel49.setBounds(40, 210, 90, 14);

        jLabel50.setText("RBC Count");
        jPanel15.add(jLabel50);
        jLabel50.setBounds(40, 250, 100, 14);

        jLabel51.setText("Amount");
        jPanel15.add(jLabel51);
        jLabel51.setBounds(40, 290, 100, 14);

        jLabel52.setText("Genetic Conditions");
        jPanel15.add(jLabel52);
        jLabel52.setBounds(40, 330, 120, 14);

        jLabel53.setText("Amount Spent");
        jPanel15.add(jLabel53);
        jLabel53.setBounds(40, 360, 80, 14);

        jLabel54.setText("jLabel18");
        jPanel15.add(jLabel54);
        jLabel54.setBounds(240, 360, 40, 14);

        jLabel55.setText("jLabel18");
        jPanel15.add(jLabel55);
        jLabel55.setBounds(230, 10, 70, 14);

        jLabel56.setText("jLabel18");
        jPanel15.add(jLabel56);
        jLabel56.setBounds(230, 50, 70, 14);

        jLabel57.setText("jLabel18");
        jPanel15.add(jLabel57);
        jLabel57.setBounds(230, 90, 70, 14);

        jLabel58.setText("jLabel18");
        jPanel15.add(jLabel58);
        jLabel58.setBounds(230, 130, 70, 14);

        jLabel59.setText("jLabel18");
        jPanel15.add(jLabel59);
        jLabel59.setBounds(230, 170, 70, 14);

        jLabel60.setText("jLabel18");
        jPanel15.add(jLabel60);
        jLabel60.setBounds(230, 210, 70, 14);

        jLabel61.setText("jLabel18");
        jPanel15.add(jLabel61);
        jLabel61.setBounds(230, 250, 70, 14);

        jLabel62.setText("jLabel18");
        jPanel15.add(jLabel62);
        jLabel62.setBounds(230, 290, 70, 14);

        jLabel63.setText("jLabel18");
        jPanel15.add(jLabel63);
        jLabel63.setBounds(240, 330, 40, 14);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel15.add(jSeparator3);
        jSeparator3.setBounds(310, 10, 10, 300);

        jLabel64.setText("Patient Remarks");
        jPanel15.add(jLabel64);
        jLabel64.setBounds(350, 10, 78, 14);

        jLabel65.setText("Doctor Remarks");
        jPanel15.add(jLabel65);
        jLabel65.setBounds(350, 160, 90, 14);

        jScrollPane3.setViewportView(jTextPane1);

        jPanel15.add(jScrollPane3);
        jScrollPane3.setBounds(350, 30, 200, 100);

        jScrollPane4.setViewportView(jTextPane2);

        jPanel15.add(jScrollPane4);
        jScrollPane4.setBounds(350, 180, 200, 100);

        jButton7.setBackground(new java.awt.Color(204, 0, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Back");
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel15.add(jButton7);
        jButton7.setBounds(330, 300, 70, 15);

        jPanel7.add(jPanel15);
        jPanel15.setBounds(0, 0, 600, 330);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Search_32px_1.png"))); // NOI18N
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel66);
        jLabel66.setBounds(560, 20, 32, 32);

        jTextField24.setText("Search");
        jPanel7.add(jTextField24);
        jTextField24.setBounds(7, 20, 540, 30);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setToolTipText("");

        jTable2.setModel(buildTableModel(res));
        jScrollPane2.setViewportView(jTable2);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(8, 59, 580, 270);

        jButton6.setBackground(new java.awt.Color(204, 0, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View Details");
        jButton6.setBorder(null);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(470, 330, 110, 30);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 10, 610, 370);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel11.add(jButton2);
        jButton2.setBounds(500, 350, 80, 29);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Password");
        jPanel11.add(jLabel13);
        jLabel13.setBounds(30, 320, 100, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Name");
        jPanel11.add(jLabel14);
        jLabel14.setBounds(30, 30, 60, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Gender");
        jPanel11.add(jLabel15);
        jLabel15.setBounds(30, 60, 70, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Date of birth");
        jPanel11.add(jLabel16);
        jLabel16.setBounds(30, 90, 100, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Height");
        jPanel11.add(jLabel17);
        jLabel17.setBounds(30, 130, 100, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Weight");
        jPanel11.add(jLabel18);
        jLabel18.setBounds(30, 160, 100, 20);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Genetics");
        jPanel11.add(jLabel19);
        jLabel19.setBounds(30, 190, 100, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Allergies");
        jPanel11.add(jLabel20);
        jLabel20.setBounds(30, 220, 100, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Blood group");
        jPanel11.add(jLabel21);
        jLabel21.setBounds(30, 250, 100, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("E-Mail");
        jPanel11.add(jLabel22);
        jLabel22.setBounds(30, 290, 100, 20);
        jPanel11.add(jSeparator1);
        jSeparator1.setBounds(30, 280, 560, 10);
        jPanel11.add(jSeparator2);
        jSeparator2.setBounds(30, 120, 560, 10);
        jPanel11.add(jTextField1);
        jTextField1.setBounds(409, 30, 170, 20);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-" }));
        jComboBox1.setBorder(null);
        jPanel11.add(jComboBox1);
        jComboBox1.setBounds(410, 250, 170, 24);
        jPanel11.add(jTextField2);
        jTextField2.setBounds(410, 130, 170, 20);
        jPanel11.add(jTextField4);
        jTextField4.setBounds(410, 160, 170, 20);
        jPanel11.add(jTextField5);
        jTextField5.setBounds(410, 190, 170, 20);
        jPanel11.add(jTextField6);
        jTextField6.setBounds(410, 290, 170, 20);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox2.setBorder(null);
        jPanel11.add(jComboBox2);
        jComboBox2.setBounds(410, 60, 170, 24);
        jPanel11.add(jTextField7);
        jTextField7.setBounds(410, 220, 170, 20);
        jPanel11.add(jPasswordField1);
        jPasswordField1.setBounds(411, 320, 170, 20);

        jPanel2.add(jPanel11);
        jPanel11.setBounds(10, 10, 610, 380);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(null);

        jTable1.setModel(buildTableModel(rss));
        jScrollPane1.setViewportView(jTable1);

        jPanel12.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 230, 250);

        jPanel13.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Gender");
        jPanel13.add(jLabel25);
        jLabel25.setBounds(20, 10, 70, 20);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox3.setBorder(null);
        jPanel13.add(jComboBox3);
        jComboBox3.setBounds(130, 10, 170, 24);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Height");
        jPanel13.add(jLabel26);
        jLabel26.setBounds(20, 40, 100, 20);
        jPanel13.add(jTextField3);
        jTextField3.setBounds(130, 40, 170, 20);
        jPanel13.add(jTextField8);
        jTextField8.setBounds(130, 70, 170, 20);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Weight");
        jPanel13.add(jLabel27);
        jLabel27.setBounds(20, 70, 100, 20);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Genetics");
        jPanel13.add(jLabel28);
        jLabel28.setBounds(20, 100, 100, 20);
        jPanel13.add(jTextField9);
        jTextField9.setBounds(130, 100, 170, 20);
        jPanel13.add(jTextField10);
        jTextField10.setBounds(130, 130, 170, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Allergies");
        jPanel13.add(jLabel29);
        jLabel29.setBounds(20, 130, 100, 20);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Blood group");
        jPanel13.add(jLabel30);
        jLabel30.setBounds(20, 160, 100, 20);

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-" }));
        jComboBox4.setBorder(null);
        jPanel13.add(jComboBox4);
        jComboBox4.setBounds(130, 160, 170, 24);

        jPanel12.add(jPanel13);
        jPanel13.setBounds(250, 10, 340, 280);

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modify");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel12.add(jButton1);
        jButton1.setBounds(510, 300, 73, 23);

        jButton3.setBackground(new java.awt.Color(204, 0, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorder(null);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel12.add(jButton3);
        jButton3.setBounds(420, 300, 73, 23);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(10, 20, 610, 340);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 630, 400));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Logout");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 135, 100, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("v1.0");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 60, 34, 14);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Delete_20px_1.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        jPanel3.add(jLabel12);
        jLabel12.setBounds(860, 0, 20, 20);

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(860, 0, 20, 20);

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Euphorium");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(0, 0, 210, 60);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Back_Arrow_32px_2.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel24);
        jLabel24.setBounds(10, 140, 32, 30);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/gjc.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 960, 180));

        setSize(new java.awt.Dimension(881, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    void insert_patient(String name,String gender, java.sql.Date dob, int height, int weight, String genetic, String allergies,
						String bgrp,String email,String pass) throws Exception {
		String sta="";
        sta = "insert into cred values(null,?,?,?,?)";
        PreparedStatement ps=co.prepareStatement(sta);
		String hashed = BCrypt.hashpw(pass, BCrypt.gensalt());
        ps.setString(1, name);
    	ps.setString(2, hashed);
        ps.setString(3,"Patient");
        ps.setString(4, email);
		ps.executeUpdate();
                String dd="select max(uid) from cred;";
                
//		sta="select uid from cred where name="+name;
//		PreparedStatement pss=co.prepareStatement(sta);
//		ResultSet rr=pss.executeQuery();
                ResultSet k=co.prepareStatement(dd).executeQuery();
                int id=0;
                if(k.next())
                    id=k.getInt(1);;
		String sql = "INSERT INTO INFO VALUES(?,?,?,?,?,?,?,?,?,?);";
		PreparedStatement pst = co.prepareStatement(sql);
		pst.setString(1, gender);
		pst.setDate(2, dob);
		pst.setInt(3, height);
		pst.setInt(4, weight);
		pst.setString(5, genetic);
		pst.setString(6, allergies);
		pst.setString(7, "0"); // THE AMOUNT THE PATIENT HAS SPENT TILL NOW; THIS WILL GET UPDATED UPON EACH VISIT
		pst.setString(8, bgrp);
		pst.setInt(9, id);
		pst.setString(10, name);
		pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Patient inserted with ID: "+id);

	}
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        reset();
        jPanel4.setBackground(new Color(204,0,51));
        jPanel6.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        reset();
        try
        {
            res=co.prepareStatement("select vid, pid, did, datetime from visits").executeQuery();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        jTable2.setModel(buildTableModel(res));
        jPanel8.setBackground(new Color(204,0,51));
        jPanel7.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        reset();
        jPanel10.setBackground(new Color(204,0,51));
        jPanel11.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        reset();
        try
        {
            rss=co.prepareStatement("select id,name from info").executeQuery();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        jTable1.setModel(buildTableModel(rss));
        jPanel9.setBackground(new Color(204,0,51));
        jPanel12.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        jPanel5.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel5.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nm=jTextField1.getText(),gene=jTextField5.getText(),all=jTextField7.getText(),eml=jTextField6.getText(),pass=jPasswordField1.getText();
        int ht=Integer.parseInt(jTextField2.getText()),wt=Integer.parseInt(jTextField4.getText());
        java.util.Date selectedDate = (java.util.Date) datePicker.getModel().getValue();
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
        
        String se=jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
        String bg=jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        try
        {
            insert_patient(nm,se,sqlDate,ht,wt, gene, all,bg,eml, pass);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //jPanel13.setVisible(true);
        int column = 0;
        int row = jTable1.getSelectedRow();
        int id = (int) jTable1.getModel().getValueAt(row, column);
        try
        {
        modify_patient(id, jComboBox3.getItemAt(jComboBox3.getSelectedIndex()), Integer.parseInt(jTextField3.getText()),
                Integer.parseInt(jTextField8.getText()), jTextField9.getText(), jTextField10.getText(), jComboBox4.getItemAt(jComboBox4.getSelectedIndex()));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Fields can't be empty");
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Patient information updated");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        jPanel14.setVisible(true);
        
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
                
		
                jPanel14.setVisible(false);
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int column = 0;
        int row = jTable1.getSelectedRow();
        int id = (int) jTable1.getModel().getValueAt(row, column);
        try
        {
        PreparedStatement pst=co.prepareStatement("delete from info where id="+id);
        PreparedStatement ps=co.prepareStatement("delete from visits where pid="+id);
        PreparedStatement pp=co.prepareStatement("delete from cred where uid="+id);
        pst.executeUpdate();
        ps.executeUpdate();
        pp.executeUpdate();
        }
        catch(Exception ee)
        {
            ee.printStackTrace();
        }
        jTable1.setModel(buildTableModel(rss));
    }//GEN-LAST:event_jButton3MouseClicked
    
    int cc(String s)
    {
        return(Integer.parseInt(s));
    }
    float ff(String s)
    {
        //System.out.println(s);
        if (s != null && !s.isEmpty())
        return(Float.parseFloat(s));
        else return 0.0f;
    }
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        try{
        insert_visit(cc(jTextField12.getText()),cc(jTextField13.getText()),ff(jTextField14.getText()),
                ff(jTextField17.getText()),ff(jTextField18.getText()),ff(jTextField19.getText()),ff(jTextField20.getText()),
                ff(jTextField16.getText()),ff(jTextField15.getText()),ff(jTextField21.getText()),jTextField22.getText(),jTextField23.getText());
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Visit recorded");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        jPanel15.setVisible(true);
        int column = 0;
        int row = jTable2.getSelectedRow();
        int id = (int) jTable2.getModel().getValueAt(row, column);
        try
        {
            PreparedStatement pst=co.prepareStatement("select bp,br,hr,bs,temp,wbc,rbc,amount,p_rem,d_rem from visits where vid="+id);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                jLabel55.setText(rs.getString(1));
                jLabel56.setText(rs.getString(2));
                jLabel57.setText(rs.getString(3));
                jLabel58.setText(rs.getString(4));
                jLabel59.setText(rs.getString(5));
                jLabel60.setText(rs.getString(6));
                jLabel61.setText(rs.getString(7));
                jLabel62.setText(rs.getString(8));
                jTextPane1.setText(rs.getString(9));
                jTextPane2.setText(rs.getString(10));
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        jPanel15.setVisible(false);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
        String sql="(SELECT vID, PID,did,datetime FROM VISITS WHERE D_REM LIKE '%"+jTextField24.getText()+"%') union (select vid,pid,did,datetime from visits where pid in (select id from info where name like '%"+jTextField24.getText()+"%'));";
        
        try{
        PreparedStatement pst= co.prepareStatement(sql);
        ResultSet rs= pst.executeQuery();
        jTable2.setModel(buildTableModel(rs));
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "No results found");
        }
        
    }//GEN-LAST:event_jLabel66MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        new Home().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked
    
    
    void insert_visit(int patient_id,
		int doctor_id ,
		float blood_pressure,
		float breathing_rate,
		float heart_rate,
		float sugar_level,
		float body_temp,
		float wbc,
		float rbc,
		float amount,
		String patient_remarks,
		String doctor_remarks)  throws Exception{

		// inserting a new visit ie already existing patient

		// schema for VISIT(vid int, pid int, did int, datetime timestamp, blood pressure float, breathing rate float, heart rate float, blood sugar levels float, body temperature float, wbc count float, rbc count float, amount float, patient remarks varchar(200), doctor remarks varchar(200))

		/*
		When the user enters his patient id, his last visit's info pops up in corresponding text boxes on the screen.
   		Info means relevant info like blood pressure, breathing rate, heart rate....onwards
   		Info like doctor id and timestamp have to be manually entered by doctor
   		visit id auto increment primary key
   		*/

		
		

		String sql = "INSERT INTO VISITS VALUES(NULL,?,?,NULL,?,?,?,?,?,?,?,?,?,?)";
		PreparedStatement pst = co.prepareStatement(sql);
		pst.setInt(1, patient_id);
		pst.setInt(2, doctor_id);
		//pst.setString(3, "null");
		pst.setFloat(3, blood_pressure);
		pst.setFloat(4, breathing_rate);
		pst.setFloat(5, heart_rate);
		pst.setFloat(6, sugar_level);
		pst.setFloat(7, body_temp);
		pst.setFloat(8, wbc);
		pst.setFloat(9, rbc);
		pst.setFloat(10, amount);
		pst.setString(11, patient_remarks);
		pst.setString(12, doctor_remarks);
                //System.out.println(pst);
		pst.executeUpdate();

		//Updating the total amount spent in the info table
		sql = "UPDATE INFO SET AMOUNT_SPENT = AMOUNT_SPENT + ? WHERE ID = ?";
		pst = co.prepareStatement(sql);
		pst.setFloat(1, amount);
		pst.setInt(2, patient_id);
		pst.executeUpdate();


	}
    
    
    void modify_patient(int patientID, String gender, int height, int weight, String genetic,
						String allergies, String bgrp) throws Exception {

		String sql = "UPDATE INFO SET GENDER  = ?, HEIGHT = ?, WEIGHT = ?, GENETIC = ?, ALLERGIES = ?, bgrp = ? WHERE ID = ?;";
		PreparedStatement pst = co.prepareStatement(sql);
		pst.setString(1, gender);
		pst.setFloat(2, height);
		pst.setFloat(3, weight);
		pst.setString(4, genetic);
		pst.setString(5, allergies);
		pst.setString(6, bgrp);
		pst.setInt(7, patientID);
		pst.executeUpdate();

	}
    
    public static DefaultTableModel buildTableModel(ResultSet rs)
        {
            Vector<String> columnNames= new Vector<String>();
            Vector<Vector<Object>> data= new Vector<Vector<Object>>();
            try{
            ResultSetMetaData metaData = rs.getMetaData();
            
            
            int columnCount = metaData.getColumnCount();
            for (int column = 1; column <= columnCount; column++) {
                columnNames.add(metaData.getColumnName(column));
            }

            
            while (rs.next()) {
                Vector<Object> vector = new Vector<Object>();
                for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                    vector.add(rs.getObject(columnIndex));
                }
                data.add(vector);
            }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            return new DefaultTableModel(data, columnNames);
            
            

        }
    void reset()
    {
        jPanel4.setBackground(new Color(51,51,51));
        jPanel8.setBackground(new Color(51,51,51));
        jPanel9.setBackground(new Color(51,51,51));
        jPanel10.setBackground(new Color(51,51,51));
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel11.setVisible(false);
        jPanel12.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
