/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

import java.awt.Color;
import java.sql.*;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abid
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form Doctor
     */
    public static DefaultTableModel buildTableModel(ResultSet rs)
        {
            Vector<String> columnNames= new Vector<String>();
            Vector<Vector<Object>> data= new Vector<Vector<Object>>();
            try{
            ResultSetMetaData metaData = rs.getMetaData();
            
            
            int columnCount = metaData.getColumnCount();
            for (int column = 1; column <= columnCount; column++) {
                columnNames.add(metaData.getColumnName(column));
            }

            
            while (rs.next()) {
                Vector<Object> vector = new Vector<Object>();
                for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                    vector.add(rs.getObject(columnIndex));
                }
                data.add(vector);
            }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            return new DefaultTableModel(data, columnNames);
            
            

        }
    static Connection co = null; 
    static int user_id = 0;
    ResultSet kk;
    public Patient(int id) {
        co = SqlConn.dbCon();
        user_id = id;
        //System.out.println(user_id);
        try
        {
        PreparedStatement pst=co.prepareStatement("select * from visits where pid="+user_id);
        kk=pst.executeQuery();
        }
        catch(Exception e)
        {
         e.printStackTrace();
        }
        initComponents();
        setValues();
        jPanel3.setBackground(new Color(0,0,0,100));
        jPanel7.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your Information");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(50, 15, 150, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Heart_with_Pulse_32px_1.png"))); // NOI18N
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 10, 32, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 250, 50);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Your Visits");
        jPanel8.add(jLabel7);
        jLabel7.setBounds(50, 15, 110, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Clock_32px.png"))); // NOI18N
        jPanel8.add(jLabel4);
        jLabel4.setBounds(10, 10, 32, 30);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 50, 250, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel8.setText("Patient ID");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(40, 10, 70, 14);

        jLabel9.setText("Name");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(40, 50, 60, 14);

        jLabel10.setText("Birthday");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(40, 90, 70, 14);

        jLabel11.setText("Sex");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(40, 130, 50, 14);

        jLabel13.setText("Height");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(40, 170, 60, 14);

        jLabel14.setText("Weight");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(40, 210, 60, 14);

        jLabel15.setText("Blood Type");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(40, 250, 80, 14);

        jLabel16.setText("Allergies");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(40, 290, 80, 14);

        jLabel17.setText("Genetic Conditions");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(40, 330, 120, 14);

        jLabel29.setText("Amount Spent");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(40, 360, 80, 14);

        jLabel18.setText("jLabel18");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(240, 360, 40, 14);

        jLabel19.setText("jLabel18");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(240, 10, 40, 14);

        jLabel20.setText("jLabel18");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(240, 50, 40, 14);

        jLabel21.setText("jLabel18");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(240, 90, 100, 14);

        jLabel22.setText("jLabel18");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(240, 130, 40, 14);

        jLabel23.setText("jLabel18");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(240, 170, 40, 14);

        jLabel24.setText("jLabel18");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(240, 210, 40, 14);

        jLabel25.setText("jLabel18");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(240, 250, 40, 14);

        jLabel26.setText("jLabel18");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(240, 290, 40, 14);

        jLabel27.setText("jLabel18");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(240, 330, 40, 14);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(20, 10, 600, 380);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jTable2.setModel(buildTableModel(kk));
        jScrollPane2.setViewportView(jTable2);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(38, 14, 570, 360);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 10, 610, 380);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 630, 400));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Euphorium");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 210, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("v1.0");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 60, 34, 14);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Delete_20px_1.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        jPanel3.add(jLabel12);
        jLabel12.setBounds(860, 0, 20, 20);

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(860, 0, 20, 20);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons8_Back_Arrow_32px_2.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel28);
        jLabel28.setBounds(10, 140, 32, 30);

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Logout");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel30);
        jLabel30.setBounds(30, 135, 100, 40);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/pediatric1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 960, 180));

        setSize(new java.awt.Dimension(881, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        reset();
        jPanel4.setBackground(new Color(204,0,51));
        jPanel6.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        jPanel5.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel5.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        reset();
        jPanel8.setBackground(new Color(204,0,51));
        jPanel7.setVisible(true);// TODO add your handling code here:
        try
        {
        PreparedStatement pst=co.prepareStatement("select * from visits where pid="+user_id);
        kk=pst.executeQuery();
        }
        catch(Exception e)
        {
         e.printStackTrace();
        }
        
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        this.dispose();
        new Home().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked
    
    void reset()
    {
        jPanel4.setBackground(new Color(51,51,51));
        jPanel8.setBackground(new Color(51,51,51));
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
    }
    
    
    void setValues()
    {
        try
        {
            String sql = "SELECT * FROM INFO WHERE ID = ?";
            PreparedStatement pst = co.prepareStatement(sql);
            pst.setInt(1,user_id);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                //The following lines of code depend on the database schema. Check once before executing
//                jTextField1 = new JTextField();
//                jLabel18 = new JLabel();
//                jTextField3 = new JTextField();
//                jTextField4 = new JTextField();
//                jTextField5 = new JTextField();
//                jTextField6 = new JTextField();
//                jTextField7 = new JTextField();
//                jTextField8 = new JTextField();
//                jTextField9 = new JTextField();
//                jTextField10 = new JTextField();
                jLabel19.setText(rs.getString(9));
                jLabel20.setText(rs.getString(10));
                jLabel21.setText(rs.getDate(2).toString());
                jLabel22.setText(rs.getString(1));
                jLabel23.setText(Integer.toString(rs.getInt(3)));
                jLabel24.setText(Integer.toString(rs.getInt(4)));
                jLabel25.setText(rs.getString(8));
                jLabel26.setText(rs.getString(6));
                jLabel27.setText(rs.getString(5));
                jLabel18.setText(Integer.toString(rs.getInt(7)));
            }
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
                
    }
    
    
    void tableValues()
    {
        //depends on the database schema
        try {
            String sql = "SELECT * FROM VISITS WHERE PID = ?";
            PreparedStatement pst = co.prepareStatement(sql);
            pst.setInt(1,user_id);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                //set table values according to table schema
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient(user_id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
